### PR TITLE
Images migration

### PR DESCRIPTION
**Pull request by jamesthebrooks**
## Changes proposed in this pull request:
- Migrated images from jekyll site

### CODE REVIEW

**Comment by jamesthebrooks** [comment]
@sknep you had the note from a closed/cancelled PR: "for these images, i just want to ask --- if this is when we're adding them to the history, this might be the best time to do any compression (pngmini?) on the filesizes. Do you have a favorite script/tool you could run these through?"

After some cursory digging, it seems that 11ty can do this by default wherever the "image" and "image_with_class" shortCodes are used.  Processing the original images in the source folder and saving them is likely a bad idea, but processing them during the eleventy build to the target folder would be a suitable solution.  IMO this is probably best discussed for the Pages template generally as we can set some defaults that can always be used rather than setting it for cloud.gov alone.

My recommendation is two-fold: 1) within Pages set a standard and implement it by default as these hooks already exist and 2) discuss images for cloud.gov more specifically within the context of the content reorg/refactor discussions that are coming

**Comment by sknep** [comment]
> "Processing the original images in the source folder and saving them is likely a bad idea"
Can you tell me why? I lack this knowledge :)

**Review by sknep — APPROVED** [review]
OK lets go with it. I think there'll be an opportunity in the future to move many of these to webp etc. Do you feel comfortable writing a backlog ticket for exploring that?

**Comment by jamesthebrooks** [comment]
> OK lets go with it. I think there'll be an opportunity in the future to move many of these to webp etc. Do you feel comfortable writing a backlog ticket for exploring that?

Not a problem.  I'll add one and link it here. I'll update this comment once created.

**Pull request merged**
