### PR TITLE
added Pages documentation section

### PR DESCRIPTION
**Pull request by jamesthebrooks**
Includes Pages' documentation section

### CODE REVIEW

**Comment by sknep** [comment]
should this page exist in this PR/branch?

https://federalist-f689d682-d20c-4d0b-af7b-c1a42fcd49f5.sites.pages.cloud.gov/preview/cloud-gov/site/chore-pages-documentation/pages/

**Comment by jamesthebrooks** [comment]
> should this page exist in this PR/branch?
> 
> https://federalist-f689d682-d20c-4d0b-af7b-c1a42fcd49f5.sites.pages.cloud.gov/preview/cloud-gov/site/chore-pages-documentation/pages/
> 
> i clicked the header link for "Pages" to get there, and i think it's the wrong URL. prob should land at
> 
> https://federalist-f689d682-d20c-4d0b-af7b-c1a42fcd49f5.sites.pages.cloud.gov/preview/cloud-gov/site/chore-pages-documentation/pages/documentation/
> 
> however, the header links there don't work. Maybe check all the nav again locally and then on the build



> should this page exist in this PR/branch?
> 
> https://federalist-f689d682-d20c-4d0b-af7b-c1a42fcd49f5.sites.pages.cloud.gov/preview/cloud-gov/site/chore-pages-documentation/pages/
> 
> i clicked the header link for "Pages" to get there, and i think it's the wrong URL. prob should land at
> 
> https://federalist-f689d682-d20c-4d0b-af7b-c1a42fcd49f5.sites.pages.cloud.gov/preview/cloud-gov/site/chore-pages-documentation/pages/documentation/
> 
> however, the header links there don't work. Maybe check all the nav again locally and then on the build

The home page is replaced now that this branch has been rebased on main.  It would not have worked until then since home page, contact, etc. was part of a different PR.  The only thing that isn't merged in this branch now is the knowledge base section... so none of that will work running this branch and you'll get a 404. Documents work for me locally.

**Comment by sknep** [comment]
ah, got it, thanks. I think the sidebar links aren't quite right, because on the preview branch they 404 at
`https://federalist-f689d682-d20c-4d0b-af7b-c1a42fcd49f5.sites.pages.cloud.gov/pages/documentation/why-use-pages/` instead of arriving at
`https://federalist-f689d682-d20c-4d0b-af7b-c1a42fcd49f5.sites.pages.cloud.gov/preview/cloud-gov/site/chore-pages-documentation/pages/documentation/why-use-pages/`

**Comment by jamesthebrooks** [comment]
> preview

I think I misunderstood your original comment... let me dig in.  Might have questions.

**Comment by jamesthebrooks** [comment]
> Details

Good to go now.  I definitely misunderstood the first go around.

**Review by sknep — APPROVED** [review]
[lookin good](https://imgur.com/gallery/w00t-wzdq3KL)

**Pull request merged**
